In [1]:
import pandas as pd
import json

In [24]:
with open ("t20_scraped_data/player_url.json") as f:
    data = json.load(f)

df_player_url = pd.DataFrame(data)

df_player_url

,playerName,team,url
0,Rohit Sharma (c),India,https://www.espncricinfo.com/cricketers/rohit-...
1,Virat Kohli,India,https://www.espncricinfo.com/cricketers/virat-...
2,Rishabh Pant â€,India,https://www.espncricinfo.com/cricketers/rishab...
3,Suryakumar Yadav,India,https://www.espncricinfo.com/cricketers/suryak...
4,Axar Patel,India,https://www.espncricinfo.com/cricketers/axar-p...
...,...,...,...
1435,Jeremy Gordon,Canada,https://www.espncricinfo.com/cricketers/jeremy...
1436,Dilon Heyliger,Canada,https://www.espncricinfo.com/cricketers/dilon-...
1437,Saad Bin Zafar,Canada,https://www.espncricinfo.com/cricketers/saad-b...
1438,Nikhil Dutta,Canada,https://www.espncricinfo.com/cricketers/nikhil...
1439,Pargat Singh,Canada,https://www.espncricinfo.com/cricketers/pargat...

In [25]:
df_player_url.drop_duplicates(subset='url',inplace=True)
df_player_url

,playerName,team,url
0,Rohit Sharma (c),India,https://www.espncricinfo.com/cricketers/rohit-...
1,Virat Kohli,India,https://www.espncricinfo.com/cricketers/virat-...
2,Rishabh Pant â€,India,https://www.espncricinfo.com/cricketers/rishab...
3,Suryakumar Yadav,India,https://www.espncricinfo.com/cricketers/suryak...
4,Axar Patel,India,https://www.espncricinfo.com/cricketers/axar-p...
...,...,...,...
1306,Henry Ssenyondo,Uganda,https://www.espncricinfo.com/cricketers/henry-...
1321,Mujeeb Ur Rahman,Afghanistan,https://www.espncricinfo.com/cricketers/mujeeb...
1330,Sadeera Samarawickrama,Sri Lanka,https://www.espncricinfo.com/cricketers/sadeer...
1360,Mohammad Nadeem,Oman,https://www.espncricinfo.com/cricketers/mohamm...
1438,Nikhil Dutta,Canada,https://www.espncricinfo.com/cricketers/nikhil...

In [26]:
df_player_url.to_json('t20_scraped_data/player_url_cleaned.json',orient="records", force_ascii=False, indent=4)